project:
  name: aco_ga_astar_mtipp
  output_dir: results

map:
  obstacle_file: data/maps/obstacle_grid.txt
  radiation_file: data/maps/radiation_grid.txt
  target_file: data/targets/targets.json
  target_source: map   # map | json
  grid_size: 1.0 # đây là kích thước của mỗi ô lưới trong đơn vị mét
  robot_velocity: 1.0 # đây là vận tốc của robot trong đơn vị mét/giây
  ri_max: 3.0
  allow_diagonal: true
  prevent_corner_cutting: true

cost_weights:
  omega_length: 0.5
  omega_risk: 0.0
  omega_energy: 0.0
  omega_collision_risk: 0.5
  turn_angle_weight: 0.7
  turn_count_weight: 0.3
  safety_c1: 0.5
  safety_radius: 5.0
  safety_max_distance: 7.0

astar:
  high_risk_avoidance: true

GA:
  population_size: 80
  max_generation: 150
  crossover_rate: 0.9
  mutation_rate: 0.08
  elite_size: 2
  gap: 0.9

ACO:
  num_ants: 50
  max_iteration: 180
  alpha: 1.0
  beta: 5.0
  rho: 0.15
  q: 100.0
  q0: 0.85
  initial_pheromone: 0.5
  ga_pheromone_bonus: 0.5
  min_pheromone: 1.0e-6
  max_pheromone: 10.0

random_seed: 42
